/**
 * Centralised user-facing UI strings.
 *
 * The UI chrome is English; the AI conversation layer is Moroccan Darija and is
 * NOT routed through this module. Keeping strings in one place means a second
 * chrome language (French was the alternative considered) can be added later
 * without touching component code.
 */
export const strings = {
  app: {
    name: 'TARKIB',
    tagline: 'AI Fabrication & Design Platform',
  },
  nav: {
    dashboard: 'Projects',
    signIn: 'Sign in',
    signUp: 'Get started',
  },
  landing: {
    heading: 'From an idea to a production-ready project.',
    body: 'Describe your fabrication project in Moroccan Darija. TARKIB turns the conversation into a structured specification, deterministic material calculations, cutting plans, costs, and the documents your client and your workshop need.',
    cta: 'Get started',
    ctaSignedIn: 'Go to your projects',
  },
  projects: {
    title: 'Projects',
    subtitle: 'Every project keeps its conversation, specification, calculations, and documents together.',
    empty: 'No projects yet.',
    emptyHint: 'Create your first project to start a conversation about it.',
    emptyArchived: 'No archived projects.',
    create: 'New project',
    creating: 'Creating…',
    titleLabel: 'Project title',
    domainLabel: 'Trade',
    titlePlaceholder: 'e.g. Restaurant facade — Casablanca',
    open: 'Open',
    rename: 'Rename',
    renaming: 'Saving…',
    save: 'Save',
    cancel: 'Cancel',
    archive: 'Archive',
    archiving: 'Archiving…',
    restore: 'Restore',
    restoring: 'Restoring…',
    delete: 'Delete permanently',
    deleting: 'Deleting…',
    deleteConfirmTitle: 'Delete this project permanently?',
    deleteConfirmBody:
      'This removes the project and everything derived from it — conversation, specification, calculations, cutting plans, costs, and documents. This cannot be undone. Archiving keeps the project recoverable instead.',
    deleteConfirmAction: 'Yes, delete permanently',
    showArchived: 'Show archived',
    hideArchived: 'Hide archived',
    createdOn: 'Created',
    updatedOn: 'Updated',
  },
  status: {
    intake: 'Intake',
    spec_approved: 'Spec approved',
    calculated: 'Calculated',
    quoted: 'Quoted',
    production_ready: 'Production ready',
    archived: 'Archived',
  },
  errors: {
    generic: 'Something went wrong.',
    retry: 'Try again',
    loadProjects: 'Could not load your projects.',
    projectNotFound: 'This project does not exist, or you do not have access to it.',
    titleRequired: 'A project title is required.',
    titleTooLong: 'Project titles are limited to 200 characters.',
  },
  chat: {
    title: 'Conversation',
    subtitle: 'Describe the project in Darija. Text, French, or English all work.',
    placeholder: 'bghit enseigne dyal restaurant…',
    send: 'Send',
    sending: 'Thinking…',
    empty: 'Tell TARKIB about the project to get started.',
    emptyHint: 'For example: "bghit enseigne dyal restaurant, 8m l3ard, alucobond noir"',
    notConfigured: 'The AI assistant is not configured on this server.',
    notConfiguredHint: 'Set OPENAI_API_KEY in your environment to enable the conversation.',
    failed: 'The assistant could not reply.',
    loadFailed: 'Could not load the conversation.',
    you: 'You',
    assistant: 'TARKIB',
  },
  materials: {
    title: 'Materials',
    subtitle: 'Your private library. Prices and suppliers are yours alone and never appear on a client document.',
    navLink: 'Materials',
    empty: 'No materials yet.',
    emptyHint: 'Add the stock you actually buy — bars, sheets, panels — with the sizes and prices from your supplier.',
    emptyFiltered: 'No materials match those filters.',
    add: 'Add material',
    edit: 'Edit',
    save: 'Save material',
    saving: 'Saving…',
    cancel: 'Cancel',
    archive: 'Archive',
    restore: 'Restore',
    delete: 'Delete',
    deleting: 'Deleting…',
    showArchived: 'Show archived',
    hideArchived: 'Hide archived',
    search: 'Search name, supplier, or notes',
    allCategories: 'All categories',
    allModels: 'All types',
    saveFailed: 'Could not save the material.',
    deleteFailed: 'Could not delete the material.',
    fields: {
      name: 'Name',
      namePlaceholder: 'e.g. Alucobond 3mm noir',
      category: 'Category',
      customCategory: 'Use a custom category',
      supplier: 'Supplier',
      measurementModel: 'How is it measured?',
      standardLength: 'Standard length (mm)',
      standardLengthHint: 'A 6 m bar is 6000',
      sheetWidth: 'Sheet width (mm)',
      sheetHeight: 'Sheet height (mm)',
      sheetHint: 'A 2.44 × 1.22 m panel is 2440 × 1220',
      thickness: 'Thickness (mm)',
      price: 'Purchase price',
      priceHint: 'What you pay your supplier',
      notes: 'Notes',
    },
    columns: {
      material: 'Material',
      stockSize: 'Stock size',
      thickness: 'Thickness',
      price: 'Price',
      supplier: 'Supplier',
    },
    archived: 'Archived',
  },
  projectMaterials: {
    title: 'Materials',
    subtitle: 'Materials used on this project, chosen from your library.',
    empty: 'No materials selected yet.',
    emptyHint: 'Add the materials this project needs. Quantities are calculated later.',
    emptyLibrary: 'Your material library is empty.',
    emptyLibraryHint: 'Add materials to your library first, then select them here.',
    goToLibrary: 'Open material library',
    add: 'Add material',
    adding: 'Adding…',
    remove: 'Remove',
    removing: 'Removing…',
    rolePlaceholder: 'What is it for? (optional)',
    notCalculated: 'Not calculated yet',
    notCalculatedHint:
      'Quantities, waste, and cost are produced by the calculation engine in a later phase. Nothing here is estimated.',
    addFailed: 'Could not add the material.',
    removeFailed: 'Could not remove the material.',
    requiredLabel: 'How much is needed?',
    requiredHint: {
      linear: 'metres',
      sheet: 'square metres',
      area: 'square metres',
      piece: 'pieces',
    },
    requiredNote: 'How did you get this? (optional)',
    saveRequirement: 'Save',
    savingRequirement: 'Saving…',
    setRequirement: 'Set quantity',
    calculate: 'Calculate materials',
    recalculate: 'Recalculate',
    calculating: 'Calculating…',
    calculateFailed: 'Could not calculate.',
    calculateBlockedTitle: 'Approve the specification first',
    resultUnits: 'To purchase',
    resultPurchased: 'Purchased',
    resultWaste: 'Waste',
    resultCost: 'Material cost',
    showWorking: 'Show working',
    hideWorking: 'Hide working',
    unsupported: 'Cannot be calculated',
    staleTitle: 'Out of date',
    stale: {
      spec_changed: 'The approved specification changed after this was calculated.',
      material_changed: 'The material was edited after this was calculated.',
      requirement_changed: 'The required quantity changed after this was calculated.',
    },
    staleAction: 'Recalculate to bring it up to date.',
    summaryCalculated: 'calculated',
    summarySkipped: 'skipped (no quantity set)',
    summaryUnsupported: 'unsupported',
    totalMaterialCost: 'Total material cost',
    internalOnly: 'Internal cost — never shown on a client document.',
    noPrices: 'Costs are not shown for your role. The quantities and waste are what you need.',
  },
  cutting: {
    title: 'Cutting plan',
    subtitle: 'Guillotine layout for sheet materials — edge-to-edge cuts a panel saw can actually make.',
    noSheetMaterials: 'No sheet materials selected for this project.',
    noSheetMaterialsHint: 'Cutting plans apply to sheet stock such as Alucobond, MDF or acrylic.',
    piecesTitle: 'Pieces to cut',
    piecesHint: 'How a facade divides into panels is your decision — seams and joins are not something the system can infer.',
    noPieces: 'No pieces added yet.',
    addPiece: 'Add piece',
    adding: 'Adding…',
    removePiece: 'Remove',
    pieceLabel: 'Label',
    pieceWidth: 'Width (mm)',
    pieceHeight: 'Height (mm)',
    pieceQuantity: 'Qty',
    allowRotation: 'May be rotated 90°',
    allowRotationHint: 'Turn off for material with a grain or print direction.',
    calculate: 'Generate cutting plan',
    recalculate: 'Regenerate',
    calculating: 'Calculating…',
    calculateFailed: 'Could not generate the cutting plan.',
    addFailed: 'Could not add the piece.',
    removeFailed: 'Could not remove the piece.',
    sheetsUsed: 'Sheets',
    waste: 'Waste',
    kerf: 'Kerf',
    edgeMargin: 'Edge margin',
    offcuts: 'Usable offcuts',
    unplacedTitle: 'Could not be placed',
    unplacedHint: 'These pieces need a different sheet size, or must be split into smaller panels — a decision only you can make.',
    diagram: 'Layout',
    rotatedNote: '↻ marks a piece turned 90°.',
    noPlan: 'No cutting plan yet.',
    settingsNote: 'Kerf and edge margin come from the material’s technical properties.',
  },
  mockups: {
    title: 'Mockups',
    subtitle: 'Presentation visuals generated from the project specification.',
    disclaimer:
      'A mockup is a presentation aid, not production geometry. It is generated by an image model and will look plausible without being dimensionally accurate — never measure from it, and never use it in place of a technical drawing.',
    notConfigured: 'Mockup generation is not configured on this server.',
    notConfiguredHint: 'Set REPLICATE_API_TOKEN to enable it.',
    generateConcept: 'Generate concept',
    generateSite: 'Place on a site photo',
    generating: 'Queuing…',
    generateFailed: 'Could not start the mockup.',
    needsSpec: 'Describe the project first — a mockup is generated from the specification.',
    noSitePhotos: 'Upload a site photo in References first.',
    choosePhoto: 'Site photo',
    empty: 'No mockups yet.',
    emptyHint: 'Generate a concept, or place the project onto a photo of the real site.',
    status: {
      queued: 'Queued',
      running: 'Generating…',
      succeeded: 'Ready',
      failed: 'Failed',
    },
    kind: { concept: 'Concept', site: 'On site' },
    remove: 'Remove',
    showPrompt: 'Show prompt',
    hidePrompt: 'Hide prompt',
    refresh: 'Refresh',
    pending: 'This runs in the background. Refresh to see the result.',
  },
  drawings: {
    title: 'Technical drawings',
    subtitle: 'Front, back, top and side views generated from the canvas geometry.',
    notCertified:
      'A technical reference drawing built from your project data — not a certified engineering drawing. Verify dimensions before fabrication.',
    empty: 'Nothing to draw yet.',
    emptyHint: 'Build the canvas first; the drawings are generated from it.',
    depthNote:
      'Side and top views need a depth on each part. Add one in the canvas to the parts that should appear.',
    unavailable: 'Not available',
    omitted: 'part(s) omitted',
    issue: 'Issue drawing',
    issuing: 'Issuing…',
    issueFailed: 'Could not issue the drawing.',
    issueNote:
      'Issuing stores a numbered copy exactly as it looks now. A production document points at an issued drawing, so the workshop copy and the record stay the same.',
    issued: 'Issued drawings',
    noneIssued: 'None issued yet.',
    version: 'Drawing',
    liveLabel: 'Live — always current',
  },
  efficiency: {
    noPrices: 'Savings are not shown for your role. Fewer units and less waste are what you can act on.',
    title: 'Material savings',
    subtitle: 'Cheaper options from your own library, calculated by re-running the cutting engines — not estimated.',
    none: 'No cheaper option found.',
    computedNote: 'Every figure below comes from running the real cutting plan against the alternative.',
    libraryOnly: 'Only stock already in your material library is compared. Add a material to check it.',
    saving: 'Saving',
    fewerUnits: 'fewer',
    lessWaste: 'less waste',
    apply: 'Switch to this material',
    applying: 'Switching…',
    applyFailed: 'Could not switch the material.',
    applyNote: 'Switching reassigns this project’s pieces and clears the old cutting plan. Regenerate the plan afterwards.',
    currentLabel: 'Now',
    alternativeLabel: 'Instead',
    unitsSuffix: 'units',
    rotationTitle: 'Rotation',
  },
  linearCutting: {
    title: 'Bar cut plan',
    subtitle: 'Cut lists for linear stock — bars, tubes and profiles.',
    noMaterials: 'No linear materials selected for this project.',
    noMaterialsHint: 'Bar cut plans apply to steel tube, aluminium profile, wood bar and similar stock.',
    cutsTitle: 'Cut lengths',
    cutsHint: 'How many of each length you need. A total length alone cannot tell the optimiser how the bars must be divided.',
    noCuts: 'No cut lengths added yet.',
    addCut: 'Add length',
    adding: 'Adding…',
    removeCut: 'Remove',
    cutLabel: 'Label',
    cutLength: 'Length (mm)',
    cutQuantity: 'Qty',
    calculate: 'Generate cut plan',
    recalculate: 'Regenerate',
    calculating: 'Calculating…',
    calculateFailed: 'Could not generate the cut plan.',
    addFailed: 'Could not add the cut length.',
    removeFailed: 'Could not remove the cut length.',
    noPlan: 'No cut plan yet.',
    barsUsed: 'Bars',
    waste: 'Waste',
    kerf: 'Kerf',
    usableRemnants: 'Reusable remnants',
    required: 'Required',
    purchased: 'Purchased',
    unplacedTitle: 'Could not be cut',
    unplacedHint: 'These lengths exceed a single bar. Joining bars is a decision about joints and strength — yours to make, not the optimiser’s.',
    diagram: 'Cut sequence',
    remnantLegend: 'Green tails are worth keeping; red are scrap.',
    settingsNote: 'Kerf and the minimum usable remnant come from the material’s technical properties.',
    supersedes: 'This is the real bar count. The material calculation divides total length by bar length, which can be lower.',
  },
  design: {
    title: 'Proposed changes',
    subtitle: 'Changes the assistant has proposed. Nothing is applied until you approve it.',
    pending: 'Waiting for your approval',
    none: 'No proposed changes.',
    noneHint: 'Ask the assistant to change the drawing — for example "zid 50cm f l3ard".',
    approve: 'Approve',
    approving: 'Approving…',
    reject: 'Reject',
    rejecting: 'Rejecting…',
    failed: 'Could not record your decision.',
    history: 'History',
    showHistory: 'Show history',
    hideHistory: 'Hide history',
    status: {
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      superseded: 'Superseded by a newer proposal',
    },
    changeCount: 'change',
    changeCountPlural: 'changes',
    specNotice:
      'This also changes an agreed dimension. Approving creates a new draft specification, which you then approve separately — that is what marks calculations and costs as out of date.',
    commandAdd: 'Add',
    commandUpdate: 'Change',
    commandRemove: 'Remove',
  },
  canvas: {
    title: 'Canvas',
    subtitle: 'A structured drawing of the project, in real millimetres — not a generated picture.',
    empty: 'Nothing on the canvas yet.',
    emptyHint: 'Build it from the approved specification, then add the parts it does not describe.',
    seed: 'Build from specification',
    reseed: 'Rebuild from specification',
    seeding: 'Building…',
    seedFailed: 'Could not build the canvas.',
    divergedTitle: 'Does not match the specification',
    divergedBody:
      'The approved specification changed after this canvas was built. The specification is what the project is; rebuild to match it, or keep this drawing and treat the difference as layout detail.',
    objects: 'Objects',
    addObject: 'Add object',
    adding: 'Adding…',
    remove: 'Remove',
    removing: 'Removing…',
    edit: 'Edit',
    save: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    saveFailed: 'Could not save the change.',
    fields: {
      type: 'Type',
      label: 'Label',
      x: 'X (mm)',
      y: 'Y (mm)',
      width: 'Width (mm)',
      height: 'Height (mm)',
      rotation: 'Rotation (°)',
      material: 'Material',
      showDimensions: 'Show dimensions',
      notes: 'Notes',
    },
    noMaterial: 'No material',
    overallSize: 'Overall',
    notEngineering:
      'A structured drawing derived from project data. Not a certified engineering drawing.',
  },
  costSettings: {
    title: 'Cost settings',
    navLink: 'Costing',
    subtitle: 'How your internal costs and client price are worked out. Private to you.',
    labor: 'Labour',
    transport: 'Transport',
    install: 'Installation',
    margin: 'Profit margin',
    tax: 'Tax / TVA',
    currency: 'Currency',
    typePercent: 'Percentage of material cost',
    typeFixed: 'Fixed amount',
    typeManual: 'Entered per project',
    percentSuffix: '%',
    save: 'Save settings',
    saving: 'Saving…',
    saved: 'Settings saved.',
    saveFailed: 'Could not save the settings.',
    marginNote: 'Applied to the internal total.',
    taxNote: 'Applied to the client subtotal (internal total + margin).',
    percentBase: 'Percentages apply to the material cost, so components never compound.',
  },
  cost: {
    title: 'Cost',
    subtitle: 'Internal cost and the resulting client price.',
    calculate: 'Calculate cost',
    recalculate: 'Recalculate cost',
    calculating: 'Calculating…',
    calculateFailed: 'Could not calculate the cost.',
    blocked: 'Calculate the project materials first.',
    empty: 'No cost calculated yet.',
    internalHeading: 'Internal breakdown',
    internalWarning: 'Private — never appears on a client document.',
    clientHeading: 'Client price',
    materials: 'Materials',
    labor: 'Labour',
    transport: 'Transport',
    install: 'Installation',
    other: 'Other expenses',
    internalTotal: 'Internal total',
    margin: 'Margin',
    clientSubtotal: 'Subtotal',
    tax: 'Tax',
    clientTotal: 'Client total',
    staleTitle: 'Out of date',
    staleBody: 'The material calculation changed after this cost was computed.',
    computedAt: 'Computed',
    expenses: 'Other expenses',
    expenseLabel: 'What was it?',
    expenseAmount: 'Amount',
    addExpense: 'Add',
    addingExpense: 'Adding…',
    removeExpense: 'Remove',
    noExpenses: 'No extra expenses.',
    settingsLink: 'Edit cost settings',
  },
  files: {
    title: 'References',
    subtitle: 'Site photos, logos, and sketches. Stored privately; links expire.',
    empty: 'No files yet.',
    emptyHint: 'Add a site photo, a logo, or a sketch of what the client wants.',
    add: 'Add files',
    uploading: 'Uploading…',
    remove: 'Remove',
    removing: 'Removing…',
    download: 'Download',
    open: 'Open',
    notConfigured: 'File storage is not configured on this server.',
    notConfiguredHint: 'Set the R2_* environment variables to enable uploads.',
    uploadFailed: 'Upload failed.',
    removeFailed: 'Could not remove the file.',
    tooLarge: 'Files must be 15MB or smaller.',
    wrongType: 'Only JPEG, PNG, WebP, HEIC, and PDF files are supported.',
    attach: 'Attach',
    attached: 'attached',
    clearAttachments: 'Clear',
    pickForMessage: 'Attach a reference to this message',
  },
  spec: {
    title: 'Specification',
    subtitle: 'Built from the conversation. This, not the chat, is what the project runs on.',
    empty: 'Nothing recorded yet.',
    emptyHint: 'The specification fills in as you describe the project.',
    missingTitle: 'Still needed',
    complete: 'Everything required has been recorded.',
    approve: 'Approve specification',
    approving: 'Approving…',
    approved: 'Approved',
    approvedNote: 'Approved on',
    approveBlocked: 'Answer the remaining questions before approving.',
    approveFailed: 'Could not approve the specification.',
    version: 'Version',
    reviewBeforeApprove: 'Review the specification above. Approving records a version snapshot that later documents refer back to.',
    fields: {
      projectType: 'Project type',
      industry: 'Industry',
      dimensions: 'Dimensions',
      quantity: 'Quantity',
      components: 'Components',
      materials: 'Materials',
      lighting: 'Lighting',
      mounting: 'Mounting',
      site: 'Site',
      lettering: 'Lettering',
      finishNotes: 'Finish',
      deadline: 'Deadline',
      notes: 'Notes',
    },
  },
  quoteSettings: {
    title: 'Quote settings',
    navLink: 'Quotes',
    subtitle: 'The company details printed on every quotation you send. Clients see all of this.',
    companyHeading: 'Company',
    companyName: 'Company name',
    companyNameNote: 'Required before a quote can be issued. A quote must not go out unattributed.',
    companyAddress: 'Address',
    companyPhone: 'Phone',
    companyEmail: 'Email',
    taxIdentifiers: 'Tax identifiers',
    taxIdentifiersNote: 'ICE, RC or IF — whatever your business is required to show.',
    logoHeading: 'Logo',
    logoNote: 'PNG, JPEG or WebP, up to 2 MB. Printed at the head of the quote.',
    logoChoose: 'Upload a logo',
    logoReplace: 'Replace logo',
    logoRemove: 'Remove',
    logoPresent: 'A logo is stored and will be printed on your quotes.',
    logoAbsent: 'No logo. Quotes will print your company name on its own.',
    logoUploading: 'Uploading…',
    logoFailed: 'Could not store the logo.',
    documentHeading: 'Document',
    primaryColor: 'Accent colour',
    primaryColorNote: 'Used for the title, the rule and the total. Leave blank for the default.',
    numberPrefix: 'Quote number prefix',
    numberPrefixNote: 'Numbers run per business, e.g. Q-2026-0001.',
    validityDays: 'Valid for (days)',
    termsText: 'Terms',
    paymentDetails: 'Payment details',
    footerText: 'Footer',
    footerNote: 'Falls back to your company name.',
    save: 'Save settings',
    saving: 'Saving…',
    saved: 'Settings saved.',
    saveFailed: 'Could not save the settings.',
  },
  quotes: {
    title: 'Client quote',
    subtitle: 'A client-facing quotation. Internal cost, margin and purchase prices never appear on it.',
    settingsLink: 'Quote settings',
    none: 'No quote yet.',
    createHeading: 'New quote',
    clientName: 'Client name',
    clientAddress: 'Client address',
    clientPhone: 'Client phone',
    clientEmail: 'Client email',
    create: 'Create draft quote',
    creating: 'Creating…',
    createFailed: 'Could not create the quote.',
    seedNote:
      'The draft starts as one line priced at the calculated client subtotal. Split it into the lines you want the client to see.',
    statusDraft: 'Draft',
    statusIssued: 'Issued',
    issuedOn: 'Issued',
    validUntil: 'Valid until',
    linesHeading: 'Lines',
    description: 'Description',
    quantity: 'Qty',
    unit: 'Unit',
    unitPrice: 'Unit price',
    lineTotal: 'Amount',
    addLine: 'Add line',
    removeLine: 'Remove',
    saveLines: 'Save lines',
    savingLines: 'Saving…',
    linesFailed: 'Could not save the lines.',
    invalidNumbers: 'Check the quantities and prices — use digits, e.g. 2.5 and 1250.00.',
    subtotal: 'Subtotal',
    tax: 'Tax / TVA',
    total: 'Total',
    calculatedSubtotal: 'Calculated client subtotal',
    divergenceAbove: 'This quote is {amount} above the calculated client price.',
    divergenceBelow: 'This quote is {amount} below the calculated client price.',
    divergenceNote: 'That is your decision to make — the figure is shown so it is not made by accident.',
    mockupHeading: 'Visual reference',
    mockupNone: 'No mockup on this quote',
    mockupNoneAvailable: 'No finished mockup to attach.',
    preview: 'Preview PDF',
    download: 'Download PDF',
    issue: 'Issue quote',
    issuing: 'Issuing…',
    issueFailed: 'Could not issue the quote.',
    issueNote: 'Issuing freezes the quote, stores the PDF and gives the client a document with this number on it. It cannot be edited afterwards.',
    blockedHeading: 'Before this quote can be issued',
    delete: 'Delete draft',
    deleteFailed: 'Could not delete the quote.',
    issuedLocked: 'Issued. Create a new quote to change anything.',
  },
  production: {
    title: 'Production package',
    subtitle:
      'The fabrication document for the workshop: drawing, material list and cutting plans. No prices — the shop floor gets quantities.',
    none: 'No package has been generated yet.',
    notesLabel: 'Production notes',
    notesPlaceholder: 'Instructions for the workshop. Frozen onto the package when you generate it.',
    preview: 'Preview package',
    generate: 'Generate package',
    generating: 'Generating…',
    generateFailed: 'Could not generate the package.',
    generateNote:
      'Each package gets its own number and is stored as it was. Generating again creates the next one rather than replacing this one.',
    blockedHeading: 'Before a package can be generated',
    gapsHeading: 'This package will say the following are missing',
    availableHeading: 'Ready to include',
    availableDrawing: 'Technical drawing',
    availableMaterials: 'Calculated material lines',
    availablePlans: 'Cutting plans',
    packagesHeading: 'Packages',
    download: 'Download',
    generatedOn: 'Generated',
    none_: '—',
  },
  suppliers: {
    title: 'Suppliers',
    navLink: 'Suppliers',
    subtitle: 'Who you buy from. Linking a material to a supplier is what lets a purchase list be grouped by who to call.',
    none: 'No suppliers yet.',
    name: 'Name',
    contact: 'Contact',
    phone: 'Phone',
    email: 'Email',
    leadTime: 'Lead time (days)',
    notes: 'Notes',
    add: 'Add supplier',
    adding: 'Adding\u2026',
    addFailed: 'Could not add the supplier.',
    archive: 'Archive',
    archiveFailed: 'Could not archive the supplier.',
    leadTimeNote: 'Stated by you. The product has no delivery history to work it out from.',
  },
  purchasing: {
    title: 'What to order',
    subtitle: 'The quantities the calculation produced, grouped by who you buy them from.',
    noSupplier: 'No supplier recorded',
    material: 'Material',
    stock: 'Stock size',
    buy: 'Buy',
    lineTotal: 'Cost',
    subtotal: 'Subtotal',
    incomplete: 'This group is not complete \u2014 see the lines above.',
    noPrices: 'Prices are not shown for your role. The quantities are what you need to order.',
    pricesNote: 'Prices are the ones the calculation used, not today\u2019s.',
  },
  profitability: {
    title: 'Projected margin',
    subtitle:
      'What this job is expected to make, from the calculation and the issued quote. The product does not know what it actually cost.',
    quoted: 'Quoted (before tax)',
    estimated: 'Estimated cost',
    margin: 'Projected margin',
    expenses: 'Recorded expenses',
    projectionNote:
      'A projection, not a result. Nothing here records invoices, hours worked or material actually used.',
  },
  analytics: {
    title: 'Business',
    navLink: 'Business',
    subtitle: 'Your own numbers, across live projects.',
    pipeline: 'Pipeline',
    outcomes: 'Quotes',
    issued: 'Issued',
    approved: 'Approved by a client',
    changesRequested: 'Changes requested',
    awaiting: 'Awaiting a reply',
    winRate: 'Approved',
    winRateUnknown: 'No quotes issued yet',
    projectedMargin: 'Projected margin',
    quotedTotal: 'Quoted, before tax',
    basedOn: 'Based on {counted} projects with both a cost and a quote.',
    excluded: '{excluded} more have one but not the other, and are left out.',
    restricted: 'Your role in this workspace does not include cost visibility.',
    stageIntake: 'Intake',
    stageSpecApproved: 'Spec approved',
    stageCalculated: 'Calculated',
    stageQuoted: 'Quoted',
    stageProductionReady: 'Production ready',
  },
  collaboration: {
    sharesTitle: 'Client link',
    sharesSubtitle:
      'A read-only page for your client. It shows the quote, the visuals and this conversation \u2014 never your costs, materials or margins.',
    noShares: 'No client link yet.',
    createHeading: 'New link',
    label: 'Who is it for?',
    labelPlaceholder: 'e.g. Cafe Milano \u2014 Youssef',
    includeQuote: 'Include the issued quote',
    includeMockups: 'Include mockups',
    includeDrawings: 'Include the technical drawing',
    allowResponses: 'Let them approve or ask for changes',
    expiresIn: 'Expires after',
    never: 'Never',
    days: 'days',
    create: 'Create link',
    creating: 'Creating\u2026',
    createFailed: 'Could not create the link.',
    noEmail:
      'No email is sent \u2014 the product has no mail provider yet. Copy the link and send it yourself.',
    copy: 'Copy link',
    copied: 'Copied',
    revoke: 'Withdraw',
    revokeFailed: 'Could not withdraw the link.',
    revoked: 'withdrawn',
    expired: 'expired',
    viewed: 'opened',
    neverViewed: 'not opened yet',
    times: 'times',

    threadTitle: 'Conversation',
    threadSubtitle: 'Your team and your client, in one thread.',
    noComments: 'Nothing yet.',
    commentPlaceholder: 'Write a message\u2026',
    post: 'Post',
    posting: 'Posting\u2026',
    postFailed: 'Could not post the message.',
    fromClient: 'client',
    approved: 'approved',
    requestedChanges: 'asked for changes',

    notifications: 'Notifications',
    noNotifications: 'Nothing new.',
    markAllRead: 'Mark all read',
  },
  workspaces: {
    title: 'Workspace',
    navLink: 'Workspace',
    subtitle: 'Who can reach this business\u2019s projects, material library and prices.',
    switchLabel: 'Workspace',
    personal: 'Personal',
    create: 'New workspace',
    createPlaceholder: 'e.g. Atelier Nour',
    creating: 'Creating\u2026',
    createFailed: 'Could not create the workspace.',
    membersHeading: 'Members',
    you: 'you',
    invitesHeading: 'Pending invitations',
    inviteHeading: 'Invite somebody',
    inviteEmail: 'Email address',
    inviteRole: 'Role',
    invite: 'Send invitation',
    inviting: 'Inviting\u2026',
    inviteFailed: 'Could not create the invitation.',
    inviteNoEmail:
      'No email is sent \u2014 the product has no mail provider yet. Copy the link below and send it yourself.',
    copyLink: 'Copy link',
    copied: 'Copied',
    revoke: 'Withdraw',
    remove: 'Remove',
    removeFailed: 'Could not remove the member.',
    roleFailed: 'Could not change the role.',
    expired: 'expired',
    yourRole: 'Your role here',
    readOnly: 'Your role does not allow managing members.',
    personalNote: 'This is your personal workspace. Create a shared one to work with other people.',
  },
  domains: {
    label: 'Trade',
    note: 'The trade decides which questions this project must answer before it can be approved, and what the assistant asks about.',
  },
  integrity: {
    title: 'Project checks',
    subtitle:
      'Everything the system can check about whether this project holds together. Nothing here is a judgement about the design.',
    allClear: 'No problems found.',
    blockers: 'Stops a document',
    warnings: 'Worth checking',
    notes: 'Worth knowing',
    readyQuote: 'Ready to quote',
    readyProduction: 'Ready for a package',
    notReadyQuote: 'Not ready to quote',
    notReadyProduction: 'Not ready for a package',
    readyNote: 'A quote is refused while its price would come from superseded figures. A package is refused while it would carry figures that are wrong — not merely absent.',
    areaSpecification: 'Specification',
    areaDesign: 'Design',
    areaMaterials: 'Materials',
    areaCutting: 'Cutting',
    areaCost: 'Cost',
    areaDocuments: 'Documents',
  },
  audit: {
    title: 'Activity',
    subtitle: 'What has been approved, issued, generated or removed on this project.',
    none: 'Nothing recorded yet.',
    show: 'Show activity',
    hide: 'Hide',
  },
  versions: {
    title: 'Version history',
    subtitle:
      'A snapshot of the whole project at each moment that mattered. Nothing here is ever rewritten.',
    none: 'No versions yet. One is recorded when you approve a specification, accept a design, issue a quote or generate a package.',
    saveHeading: 'Save a version',
    savePlaceholder: 'What are you marking? e.g. Before the client meeting',
    save: 'Save version',
    saving: 'Saving…',
    saveFailed: 'Could not save the version.',
    producedQuote: 'Produced quote',
    producedPackage: 'Produced package',
    compareWith: 'Compare with',
    compareNow: 'the project now',
    comparing: 'Comparing…',
    compareFailed: 'Could not compare these versions.',
    identical: 'Nothing differs between these two.',
    sectionSpec: 'Specification',
    sectionCanvas: 'Design',
    sectionMaterials: 'Materials',
    sectionCost: 'Cost (internal)',
    sectionReferences: 'Documents',
    added: 'added',
    removed: 'removed',
    changed: 'changed',
    close: 'Close',
    restore: 'Restore',
    restoreHeading: 'Restore this version?',
    restoreConfirm: 'Restore it',
    restoring: 'Restoring…',
    restoreFailed: 'Could not restore the version.',
    restoreCancel: 'Cancel',
    restoreChanges: 'What this would change',
    restoreConsequences: 'What restoring does',
  },
  workspace: {
    comingSoon: 'Not built yet',
    materials: 'Materials & calculations',
    materialsNote: 'Deterministic material calculations arrive in Phases 3 and 4.',
    backToProjects: '← All projects',
  },
} as const;
