/**
 * Centralised user-facing UI strings.
 *
 * The UI chrome is English; the AI conversation layer is Moroccan Darija and is
 * NOT routed through this module. Keeping strings in one place means a second
 * chrome language (French was the alternative considered) can be added later
 * without touching component code.
 */
export const strings = {
  app: {
    name: 'TARKIB',
    tagline: 'AI Fabrication & Design Platform',
  },
  nav: {
    dashboard: 'Projects',
    signIn: 'Sign in',
    signUp: 'Get started',
  },
  landing: {
    heading: 'From an idea to a production-ready project.',
    body: 'Describe your fabrication project in Moroccan Darija. TARKIB turns the conversation into a structured specification, deterministic material calculations, cutting plans, costs, and the documents your client and your workshop need.',
    cta: 'Get started',
    ctaSignedIn: 'Go to your projects',
  },
  projects: {
    title: 'Projects',
    subtitle: 'Every project keeps its conversation, specification, calculations, and documents together.',
    empty: 'No projects yet.',
    emptyHint: 'Create your first project to start a conversation about it.',
    emptyArchived: 'No archived projects.',
    create: 'New project',
    creating: 'Creating…',
    titleLabel: 'Project title',
    titlePlaceholder: 'e.g. Restaurant facade — Casablanca',
    open: 'Open',
    rename: 'Rename',
    renaming: 'Saving…',
    save: 'Save',
    cancel: 'Cancel',
    archive: 'Archive',
    archiving: 'Archiving…',
    restore: 'Restore',
    restoring: 'Restoring…',
    delete: 'Delete permanently',
    deleting: 'Deleting…',
    deleteConfirmTitle: 'Delete this project permanently?',
    deleteConfirmBody:
      'This removes the project and everything derived from it — conversation, specification, calculations, cutting plans, costs, and documents. This cannot be undone. Archiving keeps the project recoverable instead.',
    deleteConfirmAction: 'Yes, delete permanently',
    showArchived: 'Show archived',
    hideArchived: 'Hide archived',
    createdOn: 'Created',
    updatedOn: 'Updated',
  },
  status: {
    intake: 'Intake',
    spec_approved: 'Spec approved',
    calculated: 'Calculated',
    quoted: 'Quoted',
    production_ready: 'Production ready',
    archived: 'Archived',
  },
  errors: {
    generic: 'Something went wrong.',
    retry: 'Try again',
    loadProjects: 'Could not load your projects.',
    projectNotFound: 'This project does not exist, or you do not have access to it.',
    titleRequired: 'A project title is required.',
    titleTooLong: 'Project titles are limited to 200 characters.',
  },
  chat: {
    title: 'Conversation',
    subtitle: 'Describe the project in Darija. Text, French, or English all work.',
    placeholder: 'bghit enseigne dyal restaurant…',
    send: 'Send',
    sending: 'Thinking…',
    empty: 'Tell TARKIB about the project to get started.',
    emptyHint: 'For example: "bghit enseigne dyal restaurant, 8m l3ard, alucobond noir"',
    notConfigured: 'The AI assistant is not configured on this server.',
    notConfiguredHint: 'Set OPENAI_API_KEY in your environment to enable the conversation.',
    failed: 'The assistant could not reply.',
    loadFailed: 'Could not load the conversation.',
    you: 'You',
    assistant: 'TARKIB',
  },
  materials: {
    title: 'Materials',
    subtitle: 'Your private library. Prices and suppliers are yours alone and never appear on a client document.',
    navLink: 'Materials',
    empty: 'No materials yet.',
    emptyHint: 'Add the stock you actually buy — bars, sheets, panels — with the sizes and prices from your supplier.',
    emptyFiltered: 'No materials match those filters.',
    add: 'Add material',
    edit: 'Edit',
    save: 'Save material',
    saving: 'Saving…',
    cancel: 'Cancel',
    archive: 'Archive',
    restore: 'Restore',
    delete: 'Delete',
    deleting: 'Deleting…',
    showArchived: 'Show archived',
    hideArchived: 'Hide archived',
    search: 'Search name, supplier, or notes',
    allCategories: 'All categories',
    allModels: 'All types',
    saveFailed: 'Could not save the material.',
    deleteFailed: 'Could not delete the material.',
    fields: {
      name: 'Name',
      namePlaceholder: 'e.g. Alucobond 3mm noir',
      category: 'Category',
      customCategory: 'Use a custom category',
      supplier: 'Supplier',
      measurementModel: 'How is it measured?',
      standardLength: 'Standard length (mm)',
      standardLengthHint: 'A 6 m bar is 6000',
      sheetWidth: 'Sheet width (mm)',
      sheetHeight: 'Sheet height (mm)',
      sheetHint: 'A 2.44 × 1.22 m panel is 2440 × 1220',
      thickness: 'Thickness (mm)',
      price: 'Purchase price',
      priceHint: 'What you pay your supplier',
      notes: 'Notes',
    },
    columns: {
      material: 'Material',
      stockSize: 'Stock size',
      thickness: 'Thickness',
      price: 'Price',
      supplier: 'Supplier',
    },
    archived: 'Archived',
  },
  projectMaterials: {
    title: 'Materials',
    subtitle: 'Materials used on this project, chosen from your library.',
    empty: 'No materials selected yet.',
    emptyHint: 'Add the materials this project needs. Quantities are calculated later.',
    emptyLibrary: 'Your material library is empty.',
    emptyLibraryHint: 'Add materials to your library first, then select them here.',
    goToLibrary: 'Open material library',
    add: 'Add material',
    adding: 'Adding…',
    remove: 'Remove',
    removing: 'Removing…',
    rolePlaceholder: 'What is it for? (optional)',
    notCalculated: 'Not calculated yet',
    notCalculatedHint:
      'Quantities, waste, and cost are produced by the calculation engine in a later phase. Nothing here is estimated.',
    addFailed: 'Could not add the material.',
    removeFailed: 'Could not remove the material.',
    requiredLabel: 'How much is needed?',
    requiredHint: {
      linear: 'metres',
      sheet: 'square metres',
      area: 'square metres',
      piece: 'pieces',
    },
    requiredNote: 'How did you get this? (optional)',
    saveRequirement: 'Save',
    savingRequirement: 'Saving…',
    setRequirement: 'Set quantity',
    calculate: 'Calculate materials',
    recalculate: 'Recalculate',
    calculating: 'Calculating…',
    calculateFailed: 'Could not calculate.',
    calculateBlockedTitle: 'Approve the specification first',
    resultUnits: 'To purchase',
    resultPurchased: 'Purchased',
    resultWaste: 'Waste',
    resultCost: 'Material cost',
    showWorking: 'Show working',
    hideWorking: 'Hide working',
    unsupported: 'Cannot be calculated',
    staleTitle: 'Out of date',
    stale: {
      spec_changed: 'The approved specification changed after this was calculated.',
      material_changed: 'The material was edited after this was calculated.',
      requirement_changed: 'The required quantity changed after this was calculated.',
    },
    staleAction: 'Recalculate to bring it up to date.',
    summaryCalculated: 'calculated',
    summarySkipped: 'skipped (no quantity set)',
    summaryUnsupported: 'unsupported',
    totalMaterialCost: 'Total material cost',
    internalOnly: 'Internal cost — never shown on a client document.',
  },
  files: {
    title: 'References',
    subtitle: 'Site photos, logos, and sketches. Stored privately; links expire.',
    empty: 'No files yet.',
    emptyHint: 'Add a site photo, a logo, or a sketch of what the client wants.',
    add: 'Add files',
    uploading: 'Uploading…',
    remove: 'Remove',
    removing: 'Removing…',
    download: 'Download',
    open: 'Open',
    notConfigured: 'File storage is not configured on this server.',
    notConfiguredHint: 'Set the R2_* environment variables to enable uploads.',
    uploadFailed: 'Upload failed.',
    removeFailed: 'Could not remove the file.',
    tooLarge: 'Files must be 15MB or smaller.',
    wrongType: 'Only JPEG, PNG, WebP, HEIC, and PDF files are supported.',
    attach: 'Attach',
    attached: 'attached',
    clearAttachments: 'Clear',
    pickForMessage: 'Attach a reference to this message',
  },
  spec: {
    title: 'Specification',
    subtitle: 'Built from the conversation. This, not the chat, is what the project runs on.',
    empty: 'Nothing recorded yet.',
    emptyHint: 'The specification fills in as you describe the project.',
    missingTitle: 'Still needed',
    complete: 'Everything required has been recorded.',
    approve: 'Approve specification',
    approving: 'Approving…',
    approved: 'Approved',
    approvedNote: 'Approved on',
    approveBlocked: 'Answer the remaining questions before approving.',
    approveFailed: 'Could not approve the specification.',
    version: 'Version',
    reviewBeforeApprove: 'Review the specification above. Approving records a version snapshot that later documents refer back to.',
    fields: {
      projectType: 'Project type',
      industry: 'Industry',
      dimensions: 'Dimensions',
      quantity: 'Quantity',
      components: 'Components',
      materials: 'Materials',
      lighting: 'Lighting',
      mounting: 'Mounting',
      site: 'Site',
      lettering: 'Lettering',
      finishNotes: 'Finish',
      deadline: 'Deadline',
      notes: 'Notes',
    },
  },
  workspace: {
    comingSoon: 'Not built yet',
    materials: 'Materials & calculations',
    materialsNote: 'Deterministic material calculations arrive in Phases 3 and 4.',
    documents: 'Documents',
    documentsNote: 'Client quotations and production documents arrive in Phases 13 and 14.',
    backToProjects: '← All projects',
  },
} as const;
