import { prisma } from '@/lib/db';
import { ApiError, badRequest, notFound } from '@/lib/http/api';
import { assertProjectAccess, assertProjectPermission } from '@/lib/projects/service';
import { getSpec } from '@/lib/spec/service';
import { isStorageConfigured } from '@/lib/storage/config';
import { buildObjectKey } from '@/lib/storage/keys';
import { getObjectBytes, putObject } from '@/lib/storage/r2';
import type { Mockup } from '@/generated/prisma/client';
import { inngest } from '@/lib/inngest/client';
import { buildMockupPrompt } from './prompt';
import { getDomain } from '@/lib/domains/registry';
import { createReplicateProvider, isMockupConfigured } from './provider';

export type MockupKind = 'concept' | 'site';

const generationUnavailable = () =>
  new ApiError(
    503,
    'Mockup generation is not configured on this server. Set REPLICATE_API_TOKEN to enable it.',
    'mockup_not_configured'
  );

export async function listMockups(projectId: string, userId: string): Promise<Mockup[]> {
  await assertProjectAccess(projectId, userId);
  return prisma.mockup.findMany({ where: { projectId }, orderBy: { createdAt: 'desc' } });
}

/**
 * Queues a mockup.
 *
 * The row is created as `queued` before the job is dispatched, so the request
 * returns immediately with something the UI can poll. A generation that never
 * starts is then visible as a stuck job rather than silently absent.
 *
 * # Why `design.edit`, where a drawing takes `project.edit`
 *
 * A drawing is production geometry, so issuing one takes the project write
 * permission that production and designer both hold. A mockup is the opposite
 * kind of artefact: a PRESENTATION AID generated by an image model, which
 * nothing may calculate from. It belongs to the roles that shape how the job
 * looks — and `ROLE_DESCRIPTIONS` names mockups for neither production nor
 * sales.
 *
 * It is also the one write in TARKIB that SPENDS MONEY. Every request reaches
 * a paid provider, and the job retries twice. Where two permissions would both
 * be defensible, the narrower one is correct for an operation billed per call.
 *
 * Not `cost.view`: that governs seeing internal figures, and a designer does
 * not hold it. What a generation costs the business is not a number this path
 * reads, returns or stores.
 */
export async function requestMockup(
  projectId: string,
  userId: string,
  input: { kind: MockupKind; sourceFileId?: string | null }
): Promise<Mockup> {
  // First, and ahead of every side effect: no row, no job, and above all no
  // call to the image model happens for a caller without this permission.
  const { project } = await assertProjectPermission(projectId, userId, 'design.edit');
  if (!isMockupConfigured()) throw generationUnavailable();
  if (!isStorageConfigured()) {
    throw new ApiError(
      503,
      'File storage is not configured, so a generated mockup could not be saved.',
      'storage_not_configured'
    );
  }

  const specView = await getSpec(projectId, userId);
  if (Object.keys(specView.spec).length <= 1) {
    // Only specVersion present: nothing has been recorded about the project.
    throw badRequest(
      'Describe the project first. A mockup is generated from the specification, not invented.'
    );
  }

  if (input.kind === 'site') {
    if (!input.sourceFileId) {
      throw badRequest('Choose the site photograph to place the project into.');
    }
    // Scoped to the project, so a file id from elsewhere cannot be used.
    const file = await prisma.file.findFirst({
      where: { id: input.sourceFileId, projectId, status: 'ready' },
    });
    if (!file) throw notFound('Site photo');
    if (!file.mimeType.startsWith('image/')) {
      throw badRequest('A site mockup needs an image, not a document.');
    }
  }

  const { prompt, source } = buildMockupPrompt(specView.spec, input.kind, getDomain(project.domain));

  const mockup = await prisma.mockup.create({
    data: {
      projectId,
      kind: input.kind,
      sourceFileId: input.sourceFileId ?? null,
      prompt,
      promptSource: source as object,
      status: 'queued',
    },
  });

  try {
    await inngest.send({
      name: 'mockup/requested',
      data: { mockupId: mockup.id, projectId, userId },
    });
  } catch (error) {
    // The job runner is unreachable — locally that means `inngest-cli dev` is
    // not running. Without this the caller gets an opaque 500 and the row sits
    // on "queued" forever, looking like a job that will eventually run.
    await prisma.mockup.update({
      where: { id: mockup.id },
      data: {
        status: 'failed',
        failureReason: 'The background job runner could not be reached, so generation never started.',
        completedAt: new Date(),
      },
    });

    console.error('[mockup] could not dispatch the generation job', error);
    throw new ApiError(
      503,
      'The background job runner is not reachable, so the mockup was not started. In development, run `npx inngest-cli@latest dev` alongside the app.',
      'jobs_unavailable'
    );
  }

  return mockup;
}

/**
 * Runs a queued mockup. Called by the background job, never by a request.
 *
 * Every failure path records a reason on the row. A mockup card that simply
 * stays blank tells the user nothing; one that says the model timed out tells
 * them to retry.
 */
export async function runMockup(mockupId: string): Promise<void> {
  const mockup = await prisma.mockup.findUnique({ where: { id: mockupId } });
  if (!mockup) return;
  if (mockup.status === 'succeeded') return;

  const project = await prisma.project.findUnique({
    where: { id: mockup.projectId },
    select: { userId: true, domain: true },
  });
  if (!project) return;

  await prisma.mockup.update({
    where: { id: mockup.id },
    data: { status: 'running', startedAt: new Date(), failureReason: null },
  });

  try {
    if (!isMockupConfigured()) throw new Error('REPLICATE_API_TOKEN is not set.');

    const provider = createReplicateProvider();
    const specRow = await prisma.projectSpec.findFirst({
      where: { projectId: mockup.projectId },
      orderBy: { version: 'desc' },
    });

    const { parseSpecData } = await import('@/lib/spec/schema');
    const spec = parseSpecData(specRow?.data);
    const { widthPx, heightPx } = buildMockupPrompt(
      spec,
      mockup.kind as MockupKind,
      getDomain(project.domain)
    );

    let generated;
    if (mockup.kind === 'site') {
      if (!mockup.sourceFileId) throw new Error('The site photo is missing.');
      const file = await prisma.file.findUnique({ where: { id: mockup.sourceFileId } });
      if (!file) throw new Error('The site photo no longer exists.');

      const imageBytes = await getObjectBytes(file.objectKey);
      generated = await provider.generateOnSite({
        prompt: mockup.prompt,
        widthPx,
        heightPx,
        imageBytes,
        imageMimeType: file.mimeType,
      });
    } else {
      generated = await provider.generateConcept({ prompt: mockup.prompt, widthPx, heightPx });
    }

    const objectKey = buildObjectKey({
      userId: project.userId,
      projectId: mockup.projectId,
      fileId: `mockup-${mockup.id}`,
      category: 'mockups',
      mimeType: generated.mimeType,
    });
    await putObject(objectKey, generated.bytes, generated.mimeType);

    await prisma.mockup.update({
      where: { id: mockup.id },
      data: {
        status: 'succeeded',
        resultObjectKey: objectKey,
        model: generated.model,
        completedAt: new Date(),
      },
    });
  } catch (error) {
    await prisma.mockup.update({
      where: { id: mockup.id },
      data: {
        status: 'failed',
        failureReason:
          error instanceof Error ? error.message.slice(0, 500) : 'Generation failed.',
        completedAt: new Date(),
      },
    });
    // Rethrown so the job runner records the failure and can retry.
    throw error;
  }
}

export async function deleteMockup(projectId: string, userId: string, mockupId: string): Promise<void> {
  // Before the row is loaded, so a refused caller cannot tell an existing
  // mockup id from an absent one. Same permission as generating it: the two
  // halves of the same artefact.
  await assertProjectPermission(projectId, userId, 'design.edit');

  const mockup = await prisma.mockup.findUnique({ where: { id: mockupId } });
  if (!mockup || mockup.projectId !== projectId) throw notFound('Mockup');

  if (mockup.resultObjectKey && isStorageConfigured()) {
    const { deleteObject } = await import('@/lib/storage/r2');
    await deleteObject(mockup.resultObjectKey).catch(() => undefined);
  }
  await prisma.mockup.delete({ where: { id: mockup.id } });
}

/** Short-lived signed URL for a generated mockup. */
export async function getMockupImageUrl(
  projectId: string,
  userId: string,
  mockupId: string
): Promise<string> {
  await assertProjectAccess(projectId, userId);

  const mockup = await prisma.mockup.findUnique({ where: { id: mockupId } });
  if (!mockup || mockup.projectId !== projectId || !mockup.resultObjectKey) {
    throw notFound('Mockup image');
  }

  const { createSignedDownloadUrl } = await import('@/lib/storage/r2');
  return createSignedDownloadUrl(mockup.resultObjectKey);
}
