'use client';

import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { strings } from '@/lib/strings';
import { VIEW_LABELS, type ViewKind } from '@/lib/drawings/project';

export type LiveDrawingView = {
  kind: ViewKind;
  available: boolean;
  unavailableReason: string | null;
  omittedCount: number;
};

export type IssuedDrawing = {
  id: string;
  version: number;
  label: string | null;
  createdAt: string;
};

const dateFormat = new Intl.DateTimeFormat('en-GB', {
  day: 'numeric',
  month: 'short',
  hour: '2-digit',
  minute: '2-digit',
});

export function DrawingsPanel({
  projectId,
  svg,
  views,
  sceneEmpty,
  issued,
  canIssue,
}: {
  projectId: string;
  svg: string;
  views: LiveDrawingView[];
  sceneEmpty: boolean;
  issued: IssuedDrawing[];
  /** `project.edit`. Reading a drawing is open to every member; issuing is not. */
  canIssue: boolean;
}) {
  const router = useRouter();
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const anyNeedsDepth = views.some(
    (view) => !view.available && view.unavailableReason?.includes('depth')
  );

  async function issue() {
    setPending(true);
    setError(null);
    try {
      const res = await fetch(`/api/projects/${projectId}/drawings/issue`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({}),
      });
      if (!res.ok) {
        const payload = await res.json().catch(() => ({}));
        setError(payload.error ?? strings.drawings.issueFailed);
        return;
      }
      router.refresh();
    } catch {
      setError(strings.drawings.issueFailed);
    } finally {
      setPending(false);
    }
  }

  return (
    <section className="rounded-lg border border-line p-4">
      <div className="flex flex-wrap items-baseline justify-between gap-2">
        <h2 className="font-medium">{strings.drawings.title}</h2>
        {!sceneEmpty ? (
          <span className="text-xs text-ink-muted">{strings.drawings.liveLabel}</span>
        ) : null}
      </div>
      <p className="mt-1 text-sm text-ink-muted">{strings.drawings.subtitle}</p>

      {sceneEmpty ? (
        <div className="mt-4 rounded-md border border-dashed border-line px-4 py-8 text-center">
          <p className="text-sm font-medium">{strings.drawings.empty}</p>
          <p className="mt-1 text-sm text-ink-muted">{strings.drawings.emptyHint}</p>
        </div>
      ) : (
        <>
          <ul className="mt-3 flex flex-wrap gap-1.5">
            {views.map((view) => (
              <li
                key={view.kind}
                className={`rounded-full px-2 py-0.5 text-xs ${
                  view.available
                    ? 'bg-surface-muted text-ink-muted'
                    : 'border border-amber-500/40 bg-amber-500/5 text-ink-muted'
                }`}
                title={view.unavailableReason ?? undefined}
              >
                {VIEW_LABELS[view.kind]}
                {!view.available ? ` · ${strings.drawings.unavailable}` : ''}
                {view.available && view.omittedCount > 0
                  ? ` · ${view.omittedCount} ${strings.drawings.omitted}`
                  : ''}
              </li>
            ))}
          </ul>

          {anyNeedsDepth ? (
            <p className="mt-2 text-xs text-ink-muted">{strings.drawings.depthNote}</p>
          ) : null}

          {svg ? (
            <div
              className="mt-3 overflow-hidden rounded-md border border-line"
              // Generated by our own renderer from validated scene data; every
              // label is XML-escaped there.
              dangerouslySetInnerHTML={{ __html: svg }}
            />
          ) : null}

          {/* The caveat is printed on the sheet itself too, but it belongs in
              the interface as well: this is where someone decides to trust it. */}
          <p className="mt-2 text-xs text-ink-muted">{strings.drawings.notCertified}</p>

          <div className="mt-4 flex flex-wrap items-center gap-3 border-t border-line pt-4">
            <button
              type="button"
              onClick={issue}
              disabled={pending || !canIssue}
              className="rounded-md bg-accent px-4 py-2 text-sm font-medium text-accent-ink transition-opacity hover:opacity-90 disabled:opacity-60"
            >
              {pending ? strings.drawings.issuing : strings.drawings.issue}
            </button>
            <p className="text-xs text-ink-muted">{strings.drawings.issueNote}</p>
          </div>
        </>
      )}

      {error ? (
        <p role="alert" className="mt-3 text-sm text-red-600">
          {error}
        </p>
      ) : null}

      <div className="mt-4 border-t border-line pt-3">
        <p className="text-sm font-medium">{strings.drawings.issued}</p>
        {issued.length === 0 ? (
          <p className="mt-1 text-sm text-ink-muted">{strings.drawings.noneIssued}</p>
        ) : (
          <ul className="mt-2 flex flex-col gap-1 text-sm">
            {issued.map((drawing) => (
              <li key={drawing.id} className="flex flex-wrap justify-between gap-2">
                <span>
                  {strings.drawings.version} {drawing.version}
                  {drawing.label ? <span className="text-ink-muted"> — {drawing.label}</span> : null}
                </span>
                <span className="text-xs text-ink-muted">
                  {dateFormat.format(new Date(drawing.createdAt))}
                </span>
              </li>
            ))}
          </ul>
        )}
      </div>
    </section>
  );
}
