import { calculateCuttingPlan, type CuttingPieceInput } from '@/lib/calc/cutting/engine';
import { calculateLinearPlan, type LinearCutInput } from '@/lib/calc/cutting/linear';

/**
 * Material efficiency recommendations.
 *
 * # Every saving is computed, never estimated
 *
 * A recommendation is produced by re-running the SAME cutting engines against
 * the alternative and comparing the two real results. Nothing here approximates
 * a saving, and nothing here is generated by a model. This is the milestone's
 * central rule: the AI may surface and explain a recommendation, but the
 * deterministic engines decide whether it is true (PRD §13).
 *
 * # Alternatives come from the user's own library
 *
 * Only stock the user actually buys is considered. Suggesting a 4 m bar because
 * it happens to nest better would be inventing supplier availability — the
 * system has no basis to believe it can be ordered.
 */

export type CandidateSheet = {
  materialId: string;
  name: string;
  sheetWidthMm: number;
  sheetHeightMm: number;
  unitPriceCents: number;
  kerfMm: number;
  edgeMarginMm: number;
};

export type CandidateBar = {
  materialId: string;
  name: string;
  standardLengthMm: number;
  unitPriceCents: number;
  kerfMm: number;
  minUsableRemnantMm: number;
};

export type EfficiencyOutcome = {
  materialId: string;
  name: string;
  /** Sheets or bars consumed. */
  stockUnits: number;
  wastePercent: number;
  totalCostCents: number;
  /** Pieces or cuts that could not be produced from this stock at all. */
  unplacedCount: number;
};

export type Recommendation = {
  kind: 'sheet_alternative' | 'bar_alternative' | 'allow_rotation';
  current: EfficiencyOutcome;
  alternative: EfficiencyOutcome;
  /** Positive when the alternative is cheaper. Minor currency units. */
  savingCents: number;
  /** Positive when the alternative uses fewer stock units. */
  savingUnits: number;
  /** Percentage points of waste removed. Positive is an improvement. */
  wasteReductionPercent: number;
  /** Plain description of what changes, rendered from the numbers. */
  summary: string;
};

const round2 = (value: number): number => Math.round(value * 100) / 100;

/** A candidate is only worth showing if it can produce every piece. */
const isViable = (outcome: EfficiencyOutcome): boolean => outcome.unplacedCount === 0;

function sheetOutcome(
  candidate: CandidateSheet,
  pieces: CuttingPieceInput[]
): EfficiencyOutcome {
  const result = calculateCuttingPlan(pieces, {
    sheetWidthMm: candidate.sheetWidthMm,
    sheetHeightMm: candidate.sheetHeightMm,
    kerfMm: candidate.kerfMm,
    edgeMarginMm: candidate.edgeMarginMm,
  });

  return {
    materialId: candidate.materialId,
    name: candidate.name,
    stockUnits: result.sheetsUsed,
    wastePercent: result.wastePercent,
    totalCostCents: result.sheetsUsed * candidate.unitPriceCents,
    unplacedCount: result.unplaced.reduce((sum, piece) => sum + piece.quantity, 0),
  };
}

function barOutcome(candidate: CandidateBar, cuts: LinearCutInput[]): EfficiencyOutcome {
  const result = calculateLinearPlan(cuts, {
    stockLengthMm: candidate.standardLengthMm,
    kerfMm: candidate.kerfMm,
    minUsableRemnantMm: candidate.minUsableRemnantMm,
  });

  return {
    materialId: candidate.materialId,
    name: candidate.name,
    stockUnits: result.barsUsed,
    wastePercent: result.wastePercent,
    totalCostCents: result.barsUsed * candidate.unitPriceCents,
    unplacedCount: result.unplaced.reduce((sum, cut) => sum + cut.quantity, 0),
  };
}

function money(cents: number): string {
  return (cents / 100).toFixed(2);
}

function compare(
  kind: Recommendation['kind'],
  current: EfficiencyOutcome,
  alternative: EfficiencyOutcome,
  summary: string
): Recommendation {
  return {
    kind,
    current,
    alternative,
    savingCents: current.totalCostCents - alternative.totalCostCents,
    savingUnits: current.stockUnits - alternative.stockUnits,
    wasteReductionPercent: round2(current.wastePercent - alternative.wastePercent),
    summary,
  };
}

/**
 * Compares the current sheet against every other sheet in the library.
 *
 * A candidate is only recommended when it is genuinely cheaper. Fewer sheets at
 * a higher unit price can cost more, so the comparison is on total cost, not on
 * sheet count — recommending "3 sheets instead of 4" while quietly increasing
 * the bill would be worse than saying nothing.
 */
export function recommendSheetAlternatives(
  currentSheet: CandidateSheet,
  candidates: CandidateSheet[],
  pieces: CuttingPieceInput[]
): Recommendation[] {
  if (pieces.length === 0) return [];

  const current = sheetOutcome(currentSheet, pieces);
  if (!isViable(current)) return [];

  const recommendations: Recommendation[] = [];

  for (const candidate of candidates) {
    if (candidate.materialId === currentSheet.materialId) continue;

    const alternative = sheetOutcome(candidate, pieces);
    if (!isViable(alternative)) continue;
    if (alternative.totalCostCents >= current.totalCostCents) continue;

    recommendations.push(
      compare(
        'sheet_alternative',
        current,
        alternative,
        `${alternative.name} (${candidate.sheetWidthMm} × ${candidate.sheetHeightMm} mm) needs ` +
          `${alternative.stockUnits} sheet${alternative.stockUnits === 1 ? '' : 's'} instead of ` +
          `${current.stockUnits}, at ${money(alternative.totalCostCents)} instead of ` +
          `${money(current.totalCostCents)}.`
      )
    );
  }

  return recommendations.sort((a, b) => b.savingCents - a.savingCents);
}

export function recommendBarAlternatives(
  currentBar: CandidateBar,
  candidates: CandidateBar[],
  cuts: LinearCutInput[]
): Recommendation[] {
  if (cuts.length === 0) return [];

  const current = barOutcome(currentBar, cuts);
  if (!isViable(current)) return [];

  const recommendations: Recommendation[] = [];

  for (const candidate of candidates) {
    if (candidate.materialId === currentBar.materialId) continue;

    const alternative = barOutcome(candidate, cuts);
    if (!isViable(alternative)) continue;
    if (alternative.totalCostCents >= current.totalCostCents) continue;

    recommendations.push(
      compare(
        'bar_alternative',
        current,
        alternative,
        `${alternative.name} (${Number((candidate.standardLengthMm / 1000).toFixed(3))} m bar) needs ` +
          `${alternative.stockUnits} bar${alternative.stockUnits === 1 ? '' : 's'} instead of ` +
          `${current.stockUnits}, at ${money(alternative.totalCostCents)} instead of ` +
          `${money(current.totalCostCents)}.`
      )
    );
  }

  return recommendations.sort((a, b) => b.savingCents - a.savingCents);
}

/**
 * Reports what allowing rotation would save, for pieces currently pinned to one
 * orientation.
 *
 * Deliberately conservative: rotation is disabled for a reason — grain, print
 * direction, a brushed finish. The recommendation states the saving and leaves
 * the judgement to the user rather than assuming the flag was set by mistake.
 */
export function recommendRotation(
  currentSheet: CandidateSheet,
  pieces: CuttingPieceInput[]
): Recommendation | null {
  const fixed = pieces.filter((piece) => !piece.allowRotation);
  if (fixed.length === 0) return null;

  const current = sheetOutcome(currentSheet, pieces);
  if (!isViable(current)) return null;

  const rotated = pieces.map((piece) => ({ ...piece, allowRotation: true }));
  const alternative = sheetOutcome(currentSheet, rotated);
  if (!isViable(alternative)) return null;
  if (alternative.totalCostCents >= current.totalCostCents) return null;

  return compare(
    'allow_rotation',
    current,
    alternative,
    `Allowing ${fixed.length} fixed-direction piece${fixed.length === 1 ? '' : 's'} to be rotated ` +
      `would need ${alternative.stockUnits} sheet${alternative.stockUnits === 1 ? '' : 's'} ` +
      `instead of ${current.stockUnits}. Only do this if the material has no grain or print direction.`
  );
}
